# Generated by Django 4.2 on 2025-05-21 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=120)),
                ("grape_variety", models.CharField(max_length=120)),
                ("vintage", models.DateField(auto_now=True)),
                ("alcohol", models.PositiveSmallIntegerField()),
                ("sugar", models.PositiveSmallIntegerField()),
                (
                    "acidity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "bottle_volume",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("serving_temperature", models.PositiveSmallIntegerField()),
                ("aging", models.CharField(max_length=120)),
                ("pairing", models.CharField(max_length=120)),
                ("aroma", models.CharField(max_length=120)),
                ("taste", models.CharField(max_length=120)),
                ("color", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Wine",
                "verbose_name_plural": "Wines",
            },
        ),
    ]
