# Generated by Django 5.2.1 on 2025-05-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0002_wine_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="short_description",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
