name: CI

#on:
#  push:
#    branches: [ develop, main ]
#  pull_request:
#    branches: [ develop, main ]
on:
  - push
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install backend deps
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check migrations
        run: |
          cd backend
          python src/manage.py makemigrations
          python src/manage.py migrate
          python src/manage.py check

      - name: Run tests with coverage
        run: |
          cd backend
          python src/manage.py test & flake8
#          pytest --cov=src --cov-report=term-missing
